_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
langcode: en-gb
smtp_on: true
smtp_host: smtp-mail.outlook.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 60
smtp_username: noreply.mc@hkcl.in
smtp_password: nclcjbgrvjfgnpts
smtp_from: noreply.mc@hkcl.in
smtp_fromname: HKCL
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: bhumikamadan@fabwebstudio.com
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 2
prev_mail_system: php_mail
smtp_keepalive: false
