_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en-gb
uuid: 8a70cac4-9b65-470b-8ba6-b730ad03af55
name: 'Municipal Corporation'
mail: bhumikamadan@fabwebstudio.com
slogan: Yamunanagar-Jagadhri
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: null
